### ISSUE TITLE
Mining Bore Doesn't work

### ISSUE THREAD

**Issue by mewseht** [Apollo-Community/ApolloStation#261] opened 2015-09-10 20:05 UTC
The problem seems to not be the Mining Bore itself  but in how the resources that it digs up don't spawn in.  The bores work fine, but there's nothing for them to dig other then the top layer of sand that spawns in every spot of the asteroid, once it digs through this they stop because there's nothing left to dig.The reason for this I don't know the specifics of, maybe a file was misplaced or a line of code was erased or whatever. I have scanned every asteroid at random locations for resources using the Ore Detector, every time showing no resources.

**Comment by GutsySS13** [comment] 2015-09-11 13:52
same issue from May :(

https://github.com/stuicey/ApolloStation/issues/138

**Comment by Kwask** [comment] 2015-10-12 06:51
Duplicate of #138

**Closed as completed by Kwask** 2015-10-12 06:51 UTC
Labels: bug, duplicate
