### ISSUE TITLE
Cyanide pill doesn't work

### ISSUE THREAD

**Issue by bryanlavergne** [Apollo-Community/ApolloStation#406] opened 2015-11-20 02:36 UTC
KN administered cyanide, no damage.

**Comment by Kwask** [comment] 2015-11-20 04:21
Did he administer it in pill form or as an injection? Some reason cyanide pills don't seem to deposit their reagents.

**Comment by bryanlavergne** [comment] 2015-11-22 20:57
Yeah, it was via pill.

**Comment by Kwask** [comment] 2015-12-10 08:03
Duplicate of #413

**Closed as completed by Kwask** 2015-12-10 08:03 UTC
Labels: duplicate, need feedback, priority: low
