### ISSUE TITLE
Can't ghost track

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#402] opened 2015-11-18 19:51 UTC
Can't track other players as a ghost. Using the verb does nothing (like opening up the select player list dialog). Unknown cause, but seems to happen some time into a round and after having died twice?

Setting it as medium prio since as a dev I can't track people and jump to them easily when there's an issue.

**Comment by Kwask** [comment] 2015-11-18 22:03
Duplicate of #299

**Closed as completed** 2015-11-18 22:04 UTC
Labels: bug, duplicate, priority: medium
