### ISSUE TITLE
Spacepod fabricators do not update with their local console

### ISSUE THREAD

**Issue by GeckoDragon** [Apollo-Community/ApolloStation#149] opened 2015-05-17 12:40 UTC
Attempting to update spacepod fabricators to use the research data from their local console throws an error about being unable to connect. Unable to attempt repair by deconstructing and reconstructing due to bug #147

**Comment by Kwask** [comment] 2015-05-17 14:41
Duplicate of #148

**Closed as completed by Kwask** 2015-05-17 14:41 UTC
