### ISSUE TITLE
Cloning sometimes fails leading to your death inside the pod

### ISSUE THREAD

**Issue by GuidoBelluomo** [Apollo-Community/ApolloStation#421] opened 2015-11-29 22:10 UTC

**Comment by nullbear** [comment] 2015-11-30 04:04
this will happen if it's been emp'd, shuts off mid-cloning, or there is not enough oxygen in the room.

Another possible cause is that it injects too many chems.

**Comment by lmas** [comment] 2015-11-30 19:37
Duplicate of #404, closing.

**Closed as completed by lmas** 2015-11-30 19:37 UTC
