### ISSUE TITLE
Poly Direct Control Doesn't Work

### ISSUE THREAD

**Issue by minutekiwi** [Apollo-Community/ApolloStation#598] opened 2016-02-01 23:44 UTC
Assuming control of Poly pretty much breaks her. She can't be moved away from something once she sees it, so even if you take control it's like fighting just to get her to NOT go after a pen.
Not really important but a little annoying.

**Comment by stuicey** [comment] 2016-02-01 23:45
all of these animal auto control things could be fixed by simply adding `if(!client)` under simple_animal/Life()

**Comment by runedog48** [comment] 2016-02-02 19:23
Simple_Animal and Parrot's life function already contains a check to see if the mob is client controlled. Furthermore, I cannot reproduce this issue. Do you mean that taking control of them and then releasing control causes the parrot to break?
[Client Check](https://github.com/Apollo-Community/ApolloStation/blob/master/code/modules/mob/living/simple_animal/parrot.dm#L277)

**Comment by minutekiwi** [comment] 2016-02-04 13:04
Hm. I don't know what to say, in that now Poly works fine, but a spider doesn't. This was taken from just last round. The spider kept trying to go to the southeast, and I couldn't make them stop trying to do that.
As for the original issue, it was the same as this.
http://i.imgur.com/I9yLH2N.gifv

**Closed as completed** 2016-02-22 03:31 UTC
Labels: oversight, priority: low, easy to fix
