### ISSUE TITLE
Portable air scrubbers don't scrub from oxygen tanks

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#511] opened 2016-01-04 21:41 UTC
Minor annoyance in the rare case you actually want to use one with an air scrubber. A workaround is to just put the tank on as internals (if you have oxygen only at least) until it drains, but this takes a lot more time than a scrubber would have.

**Comment by Kwask** [comment] 2016-01-04 21:54
Duplicate of #346

**Comment by Kwask** [comment] 2016-01-04 21:55
Air scrubbers scrub out contaminants and only leave oxygen + nitrogen behind. If you want to drain oxygen / nitrogen from a tank, use an air pump

**Closed as completed by Kwask** 2016-01-04 21:54 UTC
Labels: its a feature!, oversight, priority: low
