### ISSUE TITLE
surgeon spawns with psychiatrist jumpsuit, can't open medical doctor lockers

### ISSUE THREAD

**Issue by TheFlyingMako** [Apollo-Community/ApolloStation#864] opened 2016-06-04 22:56 UTC

**Comment by CakeQ** [comment] 2016-06-05 02:17
This is caused by leftover alt titles from the old role-set. You can't be a surgeon as a medical doctor anymore, so make sure you change that before joining next time. Lockers have been fixed too.

**Comment by rjtwins** [comment] 2016-06-05 09:50
Kwask may have to do some sql magic to fix it globally.

**Comment by Kwask** [comment] 2016-06-05 15:57
Fixed in 4c50367f15c953cf63af50c9e852e3dd7b064d98

**Closed as completed by Kwask** 2016-06-05 15:57 UTC
