### ISSUE TITLE
Flashlights and other light sources do not always work when held.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#322] opened 2015-10-19 15:12 UTC
I've noticed that sometimes, a held light-source will not emit light as it should. This does not affect light-sources placed in the world, like a flare that has been set on the floor.

**Comment by Kwask** [comment] 2015-10-19 16:03
I noticed it happens for sure with people who were transformed into nucleations. Not sure what might be the cause of it, however.

**Comment by bryanlavergne** [comment] 2015-10-19 17:07
I'd look at user.luminosity and how it's checked with area lighting. I think there's maybe a problem that comes there. You can see that you can de-activate the held light source and re-activate it, then it works properly. An additional thought is that it may be related to maximum lighting values, as it seems to happen when holding multiple bright light sources in areas that are light off and on (I'm thinking of carrying a helmet and a lamp while on the asteroid and walking around).

**Comment by Kwask** [comment] 2015-12-03 22:06
Flashlights fixed in 3b0b9f7444414fad2474c95e8dbb4b379c8090b9

**Comment by lmas** [comment] 2016-01-01 18:02
Haven't had a problem with it for a while now, closing.

**Closed as completed by lmas** 2016-01-01 18:02 UTC
Labels: bug, priority: low

**Comment by halworsen** [comment] 2016-01-01 19:36
Should be fixed in #498 anyways.
