### ISSUE TITLE
ripleys can't fit on the new shuttles

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#158] opened 2015-05-23 23:11 UTC
Completed Ripleys can't fit on the new shuttles. they are currently being made up until the last weld and being thrown on the shuttles and then the last weld being made on the asteroid whereby they can't be returned to the station.

The only way to get completed ones there is to use the teleporter.

**Comment by Kwask** [comment] 2015-05-24 06:28
Duplicate of #157

**Closed as completed by Kwask** 2015-05-24 06:28 UTC
Labels: duplicate
