### ISSUE TITLE
Mining station suggestions.

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#69] opened 2015-04-11 21:32 UTC
Sorry for the wierd formating. And sorry for my long list. I like change!
Many of these are opinion and not fact. I love the work you did.
Most things on the list are minor. I might not have looked and looked over stuff.
- [x] 1. Isolation room should have a video screen.
- [x] 2. There are no fire alarms.
- [x] 3. There are no intercomms.
- [x] 4. Perhaps give science and mining a request console. (as if anyone uses them.)
- [x] 5. No room has a light switch.
- [ ] 6. I would love a pen to put my monkeys in so they dont walk away. 
- [x] 7. Shuttle dock airlocks are huge. If I would use the airlock as intended it would take forever to drain because it has to drain 28/34 tiles.
- [x] 8. I cant find a toolbox on the ship. (I need a welder to open rocks that have fossils. And the one in the lab is used for anomalies)
- [ ] 9. Every airlock ingame has double reinforced glass with a grill between them. Except this one.
  http://gyazo.com/93e27e9d75c7c07ad6e28b9f208adf1d
  Perhaps make it double reinforced glass with the lattices next to it?
- [x] 10. I liked the fact that there was a mech charger outside.
- [x] 11. No status displays.
- [x] 12. No fire extingishers to be found.
- [x] 13. I am not seeing or detectors. (the once that show what ores you get when you drill)
- [x] 14. I used to have flags that I could put at dig sites. I love those.
- [x] 15. One of my artifacts managed to fill the air with phoron. Can I get either portable scrubbers or the industrial ones inside the testing room?

I know this might seem like a lot but its all little stuff.

**Comment by Awantje** [comment] 2015-04-11 21:33
16 is not true anymore

**Comment by Fleegle2000** [comment] 2015-04-12 13:12
For 7 are you referring to the shared mining/science airlock? I never noticed the shuttle airlocks being that big...
I agree that that airlock is far too big to be used as intended.

Edit: never mind. I see what you mean now. Still, I think the shared airlock is a bigger priority.

**Comment by Draco16** [comment] 2015-04-12 23:41
I also have a list to contribute for the mining side of the outpost:
- [x] 1. Maintenance Door in mining hallway leads to a solid wall.
- [x] 2. Refiner and Stacker machines have no control PCs making them both useless.
- [x] 3. No light switches anywhere on the outpost making conserving electricity difficult. 
- [x] 4. Diagonal section of maintenance conveyor does not move, crates get stuck on it. 
- [x] 5. Materials get stuck in the conveyor turn after the Ore Refiner and are unable to be sent to the stacker.
- [x] 6. Only one toolbox is provided for the entire outpost, as these tools are needed for the drills outside it leaves none for inside maintenance.  
- [x] 7. Recommend adding tools, extra batteries, and battery chargers outside the outpost for maintaining the drill heads.
- [x] 8. Mining shuttle airlock is significantly larger than it needs to be.
- [x] 9. Outpost to asteroid airlock takes far too long to cycle to exterior.  (somewhere around 2 minutes or more sometimes)
- [x] 10. Airlock controls for entering the asteroid are outside the airlock making re-entering the outpost impossible.
- [x] 11. Exosuit Storage room is extremely cramped and players constantly get stuck behind ore crates and/or Ripleys.

**Comment by Fleegle2000** [comment] 2015-04-13 00:44
I played Shaft Miner earlier today and I agree with all these points. Especially 10. 9 and 8 are also major offenders.

There is also the issue I always seem to encounter where the Outpost is unpowered at the start of the round or very early on.

**Comment by Awantje** [comment] 2015-04-13 14:07
Point 9 is because the room is to big. Bigger rooms take longer to cycle.

**Comment by Fleegle2000** [comment] 2015-04-15 13:29
9 was addressed in virtue of 10 being fixed.

**Comment by Fleegle2000** [comment] 2015-04-15 13:36
On Draco's list, I'm not able to find Point 1. None of the maintenance hatchways lead to solid walls. Perhaps someone in game was building walls?

**Comment by Fleegle2000** [comment] 2015-04-15 14:27
Point 1 in Draco's list is the maintenance door with the "M" on it leading into the refinery from the hallway. There is a wall tile placed behind the door tile.

**Comment by Fleegle2000** [comment] 2015-04-15 14:31
I'd also like to note that, for some reason, in the shared airlock, the interior airlock doors open even when the pressure on the other side is low. Those doors shouldn't open unless the airlock is pressurized or the doors are forced.

**Comment by Draco16** [comment] 2015-04-15 15:43
I think the only critical issue is the lack of a refinery console. Miners can work around the other problems, but not being able to refine ore makes the entire miner department a moot point.

**Comment by stuicey** [comment] 2015-04-16 01:27
Fixed most issues listed. I will leave this as an on-going issue for new suggestions to arise

**Comment by Fleegle2000** [comment] 2015-04-17 00:38
- [x] Leaving the outpost in the science shuttle causes the shuttle to explode upon arrival at Apollo. As I was horrified to discover.
- [x] When the science shuttle docks at the outpost, the outpost airlock doors do not open.
  EDIT: I tried sending the shuttle remotely, and it turns out that what happens is the shuttle is not actually moving to the outpost. The station only thinks it has, which is why the airlock doors refuse to open.

I don't know how to make those into a fancy checklist.

lmas edit: Gotcha covered! See the [github markdown docs](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), section task lists.

**Comment by stuicey** [comment] 2015-05-21 18:30
Going to go ahead and close this. Re-open for new improvements

**Closed as completed by stuicey** 2015-05-21 18:30 UTC
Labels: suggestion, on-going
